###Recuperar todos los usuarios
GET http://localhost:3000/api/users

### Recuperar un usuario por id
GET http://localhost:3000/api/users/67a02d3012e16dd2b5114621

### Crear un usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "prueba",
  "lastname": "apellido",
  "email": "prueba@prueba.com",
  "password": "175"
}
